env:
    dev:
        aws-linux2: ami-924aa8f5dev
        ImAKey: ImADevValue
    prod:
        aws-linux2: ami-b98667deprod
        ImAKey: ImAProdValue
    test:
        aws-linux2: ami-6d263d09test
        ImAKey: ImATestValue


vpc:            vpc-dmz
subnet:         sub-bastion-a
region:         eu-west-2
# aws-linux2:     ami-924aa8f5comment
instancetype:   t2.micro
