#!/usr/bin/python3

import os
import re
from subprocess import check_output

fullpath           = os.path.abspath(__file__)
shortpath          = (__file__)
gitbasedirectory   = re.sub("/$", '', fullpath.replace(shortpath, ''))    # Retrieve the git branch base directory
gitbranchname      = re.sub("^.*/", '', gitbasedirectory)
commithistoryfile  = str(gitbasedirectory) + '/.git/.commithistory'

# We are currently working in branch $branchname
print ("Working in: " + gitbranchname)

changes = check_output(['git', 'diff', '--name-status', 'HEAD@{1}'])
change_array = str(changes.decode()).split("\n")
for i in change_array:
  change = str(i)
  # Run through the status of the files which have been updated
  if re.match('^[A-Z]\s+', change):
    operator = change[0] # re.sub('\s+.*$', '', change)
    # Check the operator.
    # M = Modified -> Will require reprovisioning
    # A = Added    -> Will require a new stack
    # D = Deleted  -> Will require removal of stack
    if operator == 'A':
      print ("Will ADD : " + change)
    elif operator == 'M':
      print ("Will MODIFY : " + change)
    elif operator == 'D':
      print ("Will DELETE : " + change)
    else:
      print ("Write to log and inform someone, because this operator is not known")
  else:
    if not re.match('^\s*$', change):
      print ("Found no operator! Cancel operation and inform user.")

